# Jekyll Configuration for GitHub Pages
# This prevents Jekyll from processing game files

# Exclude files that shouldn't be processed by Jekyll
exclude:
  - prepare_deployment.sh
  - verify_bulletproof.sh
  - setup.sh
  - "*.log"
  - node_modules/
  - vendor/

# Don't process JavaScript as Liquid templates
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Theme (optional - remove if you don't want a theme)
theme: jekyll-theme-minimal

# Treat .js files as static assets
include:
  - _config.yml

# Don't process these file types with Liquid
defaults:
  - scope:
      path: "*.js"
    values:
      layout: none
